version: '3'

services:
  rails-server:
    build: ../.
    container_name: rails-es-demo
    ports:
      - "3001:3001"
    volumes:
      - ../.:/es-demo
    command: bash -c "rm -df tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      - es-demo-network

  redis:
    image: redis:latest
    networks:
      - es-demo-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always
    ports:
      - "6033:3306"
    networks:
      - es-demo-network
  postgresql:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: secret
    restart: always
    ports:
      - "2345:5432"
    networks:
      - es-demo-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - es-demo-network
  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

networks:
  es-demo-network: