version: '3'

services:
  rails-server:
    build: ../.
    container_name: rails-es-demo
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - ./log:/app/log
      - ./tmp/pids:/app/tmp/pids
      - ./tmp/cache:/app/tmp/cache
      - ./db:/app/db
    command: bash -c "rm -df tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
#    command: bash -c "RAILS_ENV=development-legacy bundle exec rails db:create"
    networks:
      - es-demo-network

  redis:
    image: redis:latest
    networks:
      - es-demo-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    #      MYSQL_DATABASE: es-demo-development
    #      MYSQL_USER: root
    #      MYSQL_PASSWORD: password
    restart: always
    ports:
      - "6033:3306"
    networks:
      - es-demo-network
  postgresql:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: secret
    restart: always
    ports:
      - "2345:5432"
    networks:
      - es-demo-network
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.0
    ports:
      - "5601:5601"
    depends_on:
      - es01

networks:
  es-demo-network: